### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/openlauncher#1]
Moved to: https://github.com/Osiris-Team/Osiris-Team/issues/4

**Comment by Osiris-Team** [comment]
@User2564 "Hiding an application only impacts the app drawer." is this the desired functionality, or an issue to be fixed?


"Locking Desktop does not affect App Drawer (proposed descriptive name
for example: appDrawer_IgnoresDesktopLock)"is this the desired functionality, or an issue to be fixed?

**Comment by User2564** [comment]
@Osiris-Team,
Vertical App Drawer mode supports label colours. This works as expected, thanks.

Apologies for the confusion, both are desired functionality both are desired functionality / what I would consider to be an issue.
<br>With regards to "Hiding an application only impacts the app drawer.", I could have written it a lot better in hindsight, here is a practical example (with screenshots).
<br>**Before** - Desktop
<br>![Screenshot_20230629_214935](https://github.com/Osiris-Team/openlauncher/assets/96469712/6959833f-5a7e-4e59-8b3d-297b4becbafa)
<br>**Before** - App Drawer
<br>![Screenshot_20230629_214930](https://github.com/Osiris-Team/openlauncher/assets/96469712/640697e3-bd42-4677-984d-50571ab29fe9)
<br><br>**After** - Desktop
<br>![222_Screenshot_20230629_214930](https://github.com/Osiris-Team/openlauncher/assets/96469712/65ecf114-5954-49b1-97a4-786f58b4716a)
<br>**After** - App Drawer
<br>![Screenshot_20230629_221032](https://github.com/Osiris-Team/openlauncher/assets/96469712/fc15e3ed-1039-4931-ace0-782d872579d1)

**Comment by Osiris-Team** [comment]
Alright, I'll get to work then ^^

**Comment by User2564** [comment]
Rather than open issues, I have enabled discussions.
<br>Hopefully nothing blows up.

**Comment by User2564** [comment]
@Osiris-Team
<br>For some reason if I hide an application that is inside a Desktop group e.g.
<br>![image](https://github.com/Osiris-Team/openlauncher/assets/96469712/9685c5ea-89b5-4265-92fa-fab922d10ccb)
<br>It is deleted, when the desired output is hiding an application to only affected the App Drawer.
<br>If hidden via the Desktop -> Settings -> "Hide Apps", no message is printed.
<br>However hiding it via App Drawer -> hold -> Hide, produces the following message.
<br>![Screenshot_20230630_191227](https://github.com/Osiris-Team/openlauncher/assets/96469712/115bae22-1604-42ca-84e6-fe3d61b548c9)

Attempting to debug it myself has not gone so well.

**Comment by Osiris-Team** [comment]
@User2564 I did some testing and pushed another commit (0567afc2590860b00d5dba76adb77cf2e0b48ea0) which seems to fix it.

I think you should be able to reopen the pull request and then merge that commit?

**Comment by Osiris-Team** [comment]
![image](https://github.com/Osiris-Team/openlauncher/assets/59899645/6c8c897c-7e97-4be8-9d44-f83b47e551ae)

@User2564 I'm now 3 hours into this and tried to change the styles programmatically (which didn't work, because I couldn't get the file picker view), and the above is the best I could do only using xml. 

The problems with xml are that I don't know how to get the currently selected themes values, and I don't know how to change the color of the top bars label (text is gray, but should be white), only via the available xml in the screenshot.

I have an idea how to fix this programmatically, which would involve registerActivityLifecycleCallbacks (which would only work on android Q devices) to listen for the created file picker activity, then loop through its children and set the styles.

How should I proceed?

**Comment by User2564** [comment]
@Osiris-Team
<br>Apologies for the delay,
>I don't know how to get the currently selected themes values, and I don't know how to change the color of the top bars label (text is gray, but should be white), only via the available xml in the screenshot.

Hopefully the following serves as a useful starting point: https://github.com/spacecowboy/NoNonsense-FilePicker
<br>Source: `implementation 'com.nononsenseapps:filepicker:4.2.1'` - `openlauncher\app\build.gradle`
>I think you should be able to reopen the pull request and then merge that commit?

I don't think so, simply ended up creating a new MR and then repeating the initial process of linking both.
<br>Edit: Works as desired, thanks.

<br>Else I would recommend:
- Implementing your proposal but gating it behind a Q or greater OS version check with the else path being the current behavior.
- Include a end user viewable comment noting that the "Primary Colour" only applies to the "backup/restore views" on Android Q / 10 or later.

Any thoughts?

**Comment by Osiris-Team** [comment]
@User2564 Thanks! I was able to change the text color to white for the top bar, via XML.
Just pushed some changes still working on the color.

I thought I was done until I scrolled and saw this:
![image](https://github.com/Osiris-Team/openlauncher/assets/59899645/913f735a-b691-47cf-8c09-b0813ed6e64d)
Fixed now.

**Comment by Osiris-Team** [comment]
@User2564 did you receive my email about the payment change?

**Comment by Osiris-Team** [comment]
@User2564 about the "Locking Desktop does not affect App Drawer".
Should the app be draggable to the desktop, or only display the menu overlay (the one with hide, uninstall)?

**Comment by Osiris-Team** [comment]
Btw I finished everything, is there more to do?

**Comment by User2564** [comment]
@Osiris-Team,
Apologies for the delay.
>did you receive my email about the payment change?

Yes. Unfortunately, I can not tell at a quick glance what the proposed changes are.
Updated [Contract.odt](https://github.com/Osiris-Team/openlauncher/files/12063677/Contract.odt)

It would appear that the email I sent (which according to my email client) on 2023-07-05, 12:06:59 to osiris_support[at]proton[dot]me email has been lost in the void. I have included it in full below for your reference.

------------------------------------------------------------
Hi Arman,
Thanks for your email.
Apologies for my lack of clarity.
After some thought, I wish to propose the following additional supplemental changes.

Payment
-------------------------------------
To be made to DC's PayPal email upon which of the following comes first (starting from June 2023);

- Completion of end user testing and acceptance.

- End of (the current) month.

(If the latter, payment will be made) within the first (full and clear) week of the following month. E.g the week starting Monday 3rd of July 2023

...

Scope of work
-------------------------------------
Drop: “ Locking Desktop does not affect App Drawer...”
Add
---------------
Work on resolving the following issues with the end goal of getting said changes up-streamed and released, ideally or if possible sooner rather than later.

github.com/VinylMusicPlayer/VinylMusicPlayer/issues/737 / github.com/VinylMusicPlayer/VinylMusicPlayer/issues/736

github.com/VinylMusicPlayer/VinylMusicPlayer/issues/727

gitlab.com/sultanahamer/OpenContacts - Add Auto-rotate / landscape support

Any thoughts?

As a sign of good faith / will, June's invoice of
144.83 USD / 233.76 NZD / 126.20 Euro has been paid with the payment type as "For friends and family".

It would be appreciated if you could also send a screenshot the payment recipient's view of a PayPal payment.

Kind regards,
James

------------------------------------------------------------

>about the "Locking Desktop does not affect App Drawer".
>Should the app be draggable to the desktop, or only display the menu overlay (the one with hide, uninstall)?

To hopefully be clearer; initially the end goal was that if the if the desktop is locked, then the menu overlay within the app drawer is unaffected.

However upon further thought, draggable would be great as well.
>Btw I finished everything, is there more to do?

Work on resolving the following issues with the end goal of getting said changes up-streamed and released, ideally or if possible sooner rather than later.

github.com/VinylMusicPlayer/VinylMusicPlayer/issues/737 / github.com/VinylMusicPlayer/VinylMusicPlayer/issues/736

github.com/VinylMusicPlayer/VinylMusicPlayer/issues/727

gitlab.com/sultanahamer/OpenContacts - Add Auto-rotate / landscape support

Any thoughts?

**Comment by Osiris-Team** [comment]
@User2564 Hey, no problem and yeah guess your mails didn't come through :/

I moved the contract to github so that the changelog is separate and the changes easier to view. https://github.com/Osiris-Team/Osiris-Team/blob/main/open_source_dev_contract.md

* Edit: Its probably better to just read the full contract above, instead of the changes I mentioned below since some may be outdated.

Some things I changed / Some things I am unsure about:

I removed `1)	Completion of end user testing and acceptance.` to simplify it and receive only one payment per month. I don't mind waiting until the month finishes for the payment to come.

I think you meant `first` instead of `final`? Here: `2)	During the final week of the current month an invoice will be sent via email to The Client covering the prior month, starting from July 2023 and continuing until contract termination by either party.`
I changed it to:
`2)	During the first week of the current month Developer Consultant will send an invoice via email to The Client covering the prior month, starting from July 2023 and continuing until contract termination by either party.
`

I also removed `The above rate is subject to agreement between all applicable parties.`, since we already agree by signing the contract and I think there is no additional step needed to agree on the payment then.

I also noticed the timing section was missing haha, added that.

Also added this to scope of work:
> 1. Developer Consultant may reject to work on a or multiple tasks.
    - In this case the Developer Consultant is also obligated to give a clear and concise reason.
    - If this happens after working on the task, those hours must not be paid by the Client. 

You can create a pull/merge request with your changes to the contract and we can discuss it there.

Tell me what you think 👍

**Comment by Osiris-Team** [comment]
@User2564 Just sent you an email with the signed contract.
Appreciate the wage increase btw.
Also gonna start working on the new tasks asap.

> To hopefully be clearer; initially the end goal was that if the if the desktop is locked, then the menu overlay within the app drawer is unaffected. However upon further thought, draggable would be great as well.

Ok, then there should be no further changes necessary to the existing MR.
